#!/bin/bash

print_help() {
	
	echo -e "Usage: ./$(basename $0) <iface>"

}

if [ $# -eq 0 ]; then
	print_help
	exit 1
fi

iface=$1

if ifconfig $iface >/dev/null 2>&1; then 
	
	if [[ "$iface" == *"eth"*  ]]; then

		sudo ifconfig $iface up 

		sudo macchanger -r -p $iface 1&>/dev/null 

		sudo dhclient $iface

	elif [[ "$iface" == *"wlan"* ]]; then
		
		sudo ifconfig $iface up

		sudo wpa_supplicant -B -c /etc/wpa_supplicant.conf -i $iface 1&>/dev/null

		sudo dhclient $iface
	fi

	echo -e "Got \033[32m$(ip a show $iface | grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' -o | head -n 1)\033[0m address on $iface iface!"

else
	echo -e "Entered iface '$iface' \033[31mnot exists!\033[0m"

fi