#!/bin/bash

if [ $# -eq 1 ]; then 

	iface=$1

	if [ $(ifconfig $iface 2&>/dev/null) ]; then 
		
		if [[ "$iface" == *"eth"*  ]]; then

			sudo ifconfig $iface up 

			sudo macchanger -r -p $iface 1&>/dev/null 

			sudo dhclient $iface

		elif [[ "$iface" == *"wlan"* ]]; then
			
			sudo ifconfig $iface up

			sudo wpa_supplicant -B -c /etc/wpa_supplicant.conf -i $iface 1&>/dev/null

			sudo dhclient $iface
		fi

		echo "Got $(ip a show $iface | grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' -o | head -n 1) address on $iface iface!"
	
	else
		echo "Incorrect parameters!"

	fi

else
	echo "Missing parameters: net-interface"
fi