#!/bin/bash

iface=$1

if [[ "$iface" == *"eth"*  ]]; then

	sudo ifconfig $iface up 

	sudo macchanger -r -p $iface 1&>/dev/null 

	sudo dhclient $iface

elif [[ "$iface" == *"wlan"* ]]; then
	
	sudo ifconfig $iface up

	sudo wpa_supplicant -B -c /etc/wpa_supplicant.conf -i $iface 1&>/dev/null

	sudo dhclient $iface
	
else 
	echo "Missing parameters: net-interface"
	echo " or"
	echo "wrong parameters (should be eth* or wlan*)"
fi

echo "Got $(ip a show $iface | grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' -o | head -n 1) address on $iface iface!"
