#!/bin/bash

#Created by @iank13
#Script for check connection. 
#It check ping to Google and some external IP's info.

echo -n "Ping to Google: "

if [ $(ping 8.8.8.8 -c 1 | grep 64 -o | awk '{print $1}')  == "64" ];then 

	echo -e "\033[32m[OK]\033[0m" 

else

	echo -e "\033[31m[X]\033[0m"

fi

if response=$(curl -s ipinfo.io); then

	#IP	
	echo -n "External IP: "
	echo $response | jq '.ip' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | awk '{print "\033[32m" $0 "\033[0m"}'
	
	#Country
	echo -n "Country: "
	echo $response | jq '.country' | sed 's/"//g' | awk '{print "\033[32m" $0 "\033[0m"}'

	#City
	echo -n "City: "
        echo $response | jq '.city' | sed 's/"//g' | awk '{print "\033[32m" $0 "\033[0m"}'

else 
	echo -e "\033[31mCouldn't check external IP!\033[0m"
fi
